name: Pelican site CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: "Set up Python 3.12"
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pelican pyyaml beautifulsoup4 ghp-import
        git clone --depth=1 --single-branch --branch mechmotum https://github.com/mechmotum/pelican-alchemy.git
        git clone --depth=1 https://github.com/getpelican/pelican-plugins.git
    - name: Build the website
      run: |
        pelican -D -v --fatal errors -s publishconf.py -o output
    - name: Deploy the website
      if: ${{ github.event_name == 'push' }}
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email mechmotum@users.noreply.github.com
        git remote add deploy "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/moorepants/me41035.git"
        ghp-import --no-history -r deploy -b gh-pages -m "Updated via Github Actions" -p output
